[package]
name = "firehose-rs"
version = "0.1.0"
edition = "2021"
description = "Firehose client for Rust"
authors = ["Joseph Livesey <joseph@semiotic.ai>"]
license = "Apache-2.0"
repository = "https://github.com/semio-ai/firehose-rs"

[lib]
path = "src/lib.rs"
name = "firehose_rs"

[dependencies]
prost = "0.13.1"
prost-wkt = "0.6.0"
prost-wkt-types = "0.6.0"
serde = "1.0.208"
tonic = "0.12.0"

[build-dependencies]
prost-build = "0.13.1"
tonic-build = "0.12.0"
